version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: widen
  allow:
  - dependency-type: development
  ignore:
  - dependency-name: rollup
    versions:
    - 2.38.2
    - 2.42.1
    - 2.43.0
    - 2.45.1
  - dependency-name: svelte
    versions:
    - 3.32.2
    - 3.32.3
    - 3.33.0
    - 3.34.0
    - 3.35.0
    - 3.36.0
